[package]
name = "example"
version = "0.1.0"
authors = ["Steven Le Rouzic <steven.lerouzic@gmail.com>"]
edition = "2018"

[dependencies]
macroserde = { path = "../macroserde" }
macroserde-json = { path = "../macroserde-json" }
macroserde-msgpack = { path = "../macroserde-msgpack" }